---
pagetitle: "Harvest"
---

```{r setup, include=F}
knitr::opts_chunk$set(echo=F, message=F, warning=F, error=F)
source(here::here("infographiqR.R"))
```

`r insert_info(csv = here::here("data/gsheets/modals.csv"))`


### {.tabset}

#### Fishing, personal use

`r insert_figure("human-connections_harvest.html", "figures/Figure ES.SH.1 Subsistence_edit.png")`

#### Map - catch reporting areas fish/shellfish

`r insert_figure("human-connections_harvest.html", "figures/Figure ES.CH1a. marine area vs ocnms boundary.png")`

#### Map - catch reporting areas salmon

`r insert_figure("human-connections_harvest.html", "figures/Figure ES.CH1b. salmon areas vs ocnms boundary.png")`

#### Top 11 species by landings

`r insert_figure("human-connections_harvest.html", "figures/ES.CH.2a.png")`

#### Top 11 species by value

`r insert_figure("human-connections_harvest.html", "figures/ES.CH.2b.png")`

#### Top 5 species by $

`r insert_figure("human-connections_harvest.html", "figures/ES.CH.4.png")`

#### Top 5 species by weight

`r insert_figure("human-connections_harvest.html", "figures/ES.CH.3.png")`

#### Trends - Black rockfish retained

`r insert_figure("human-connections_harvest.html", "figures/CR_app_blackrockfish.JPG")`

#### Trends - Dungeness crab catch, revenue

`r insert_figure("human-connections_harvest.html", "figures/Appendix Figure ES.CH.3 D crab_edit.png")`

#### Trends - Halibut biomass

`r insert_figure("human-connections_harvest.html", "figures/Appendix Figure ES.CH.1 IPHC catch area_edit.png")`

#### Trends - Halibut retained

`r insert_figure("human-connections_harvest.html", "figures/CR_app_halibut.JPG")`

#### Trends - Lingcod retained

`r insert_figure("human-connections_harvest.html", "figures/CR_app_lingcod.JPG")`

#### Trends - Razor Clam harvest and value

`r insert_figure("human-connections_harvest.html", "figures/ES.CR.5.png")`

#### Trends - Revenue, salmon troll

`r insert_figure("human-connections_harvest.html", "figures/Appendix Figure ES.CH.9 Total revenue by management group_edit.png")`

#### Trends - Salmon retained

`r insert_figure("human-connections_harvest.html", "figures/CR_app_salmon.JPG")`

#### Trends - Status of goundfish stocks

`r insert_figure("human-connections_harvest.html", "figures/Graph S.P.4.1.png")`

#### Trends - Tuna retained

`r insert_figure("human-connections_harvest.html", "figures/CR_app_tuna.JPG")`

#### Trends - Vessels, salmon troll fleet

`r insert_figure("human-connections_harvest.html", "figures/Appendix Figure ES.CH.8 Troll vessels_edit.png")`

#### Trends - Whiting catch

`r insert_figure("human-connections_harvest.html", "figures/Appendix Figure ES.CH.2 Whiting_edit.png")`

#### Trends - Yellowtail rockfish retained

`r insert_figure("human-connections_harvest.html", "figures/CR_app_YTrockfish.JPG")`
