---
pagetitle: "Seabirds"
---

```{r setup, include=F}
knitr::opts_chunk$set(echo=F, message=F, warning=F, error=F)
source(here::here("infographiqR.R"))
```

`r insert_info(csv = here::here("data/gsheets/modals.csv"))`


# {.tabset}
  
## At-sea surveys

### {.tabset}

#### Maps - Marbled Murrelet

`r insert_figure("pelagic_seabirds.html", "figures/S.LR.13.12 - Marbled murrelet densities 2000-2019 Map.jpg")`

#### Trends - Cassin's Auklet

`r insert_figure("pelagic_seabirds.html", "figures/Appendix S.LR.13.10 - Density anomalies for Cassins Auklet 2003-2019.jpg")`

#### Trends - Marbled Murrelet

`r insert_figure("pelagic_seabirds.html", "figures/Figure S.LR.13.10 Panel 2 - Marbled murrelet densities 2000-2019 Figure.jpg")`

#### Trends - Tufted Puffin

`r insert_figure("pelagic_seabirds.html", "figures/S.LR.13.11 - Tufted puffin encounters 2001-2018.jpg")`
  
## Beach carcass surveys

### {.tabset}

#### Trends - Cassin's Auklet carcasses

`r insert_figure("pelagic_seabirds.html", "figures/Appendix S.LR.13.11 - Encounter rates for dead Cassins auklet 2001-2018.jpg")`

#### Trends - Common Murre carcasses

`r insert_figure("pelagic_seabirds.html", "figures/Appendix S.LR.13.9 - Encounter rates for dead common murres 2008-2020.jpg")`
