---
pagetitle: "Larvae and zooplankton"
---

```{r setup, include=F}
knitr::opts_chunk$set(echo=F, message=F, warning=F, error=F)
source(here::here("infographiqR.R"))
```

`r insert_info(csv = here::here("data/gsheets/modals.csv"))`


### {.tabset}

#### Maps - Larvae and zooplankton stations

`r insert_figure("pelagic_larvae-zooplankton.html", "figures/S.LR.Q15.3 - Map Pelagic larvae and zooplankton species richness, diversity and evenness_edit.jpg")`

#### Maps - Phytoplankton

`r insert_figure("pelagic_larvae-zooplankton.html", "figures/S.LR.Q15.2 - Map Diatom and dinoflagellate species richness anomalies for 2009-2016 offshore of Newport OR_edit.jpg")`

#### Trends - Copepods

`r insert_figure("pelagic_larvae-zooplankton.html", "figures/S.LR.13.1 - Copepod Biomass 1996-2020.jpg")`

#### Trends - Larvae and zooplankton diversity

`r insert_figure("pelagic_larvae-zooplankton.html", "figures/S.LR.Q15.3 - Figure Pelagic larvae and zooplankton species richness, diversity and evenness.jpg")`

#### Trends - Phytoplankton diversity

`r insert_figure("pelagic_larvae-zooplankton.html", "figures/S.LR.Q15.2 - Figure Diatom and dinoflagellate species richness anomalies for 2009-2016 offshore of Newport OR.jpg")`
