---
pagetitle: "Barnacles"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=F}
knitr::opts_chunk$set(echo=F, message=F, warning=F, error=F)
source(here::here("infographiqR.R"))
```

`r insert_info(csv = here::here("data/gsheets/modals.csv"))`

## {.tabset}

### Map of Sites

```{r}
map_nms_sites("ocnms")
```


### Acorn Barnacles (_Chthamalus dalli/fissus/Balanus glandula_) {.active}

```{r}
d0_csv         <- here("data/rocky-intertidal_MARINe/sanctuary_species_percentcover.csv")
d_csv         <- here("data/rocky-intertidal_MARINe/sanctuary_species_percentcover_new.csv")

d0 <- readr::read_csv(d0_csv)
d  <- readr::read_csv(d_csv)

# readr::read_csv(d_csv) %>%
#   mutate(
#     date = as.Date(date, "%m/%d/%y")) %>% 
#   readr::write_csv(d_csv)

# detach("package:onmsR", unload = TRUE)
# devtools::load_all("~/github/noaa-onms/onmsR")

plot_intertidal_nms(d_csv, "OCNMS", "CHTBAL", "Acorn Barnacles") %>%
  dyLegend(show="follow")
```


### Acorn Barnacles (_Chthamalus dalli/fissus/Balanus glandula_), target = balanus

```{r}
plot_intertidal_nms(d_csv, "OCNMS", "CHTBAL", "Acorn Barnacles [target = balanus]", c("balanus", "chthamalus_balanus")) %>% 
  dyLegend(show="follow")
```


