---
pagetitle: "Ochre stars"
---

```{r setup, include=F}
knitr::opts_chunk$set(echo=F, message=F, warning=F, error=F)
source(here::here("infographiqR.R"))
```

`r insert_info(csv = here::here("data/gsheets/modals.csv"))`


### {.tabset}

#### Trends - abundance (MARINe)

`r insert_figure("rocky-shore_ochre-star.html", "figures/S.LR.12.1 - Abundance of Pisaster ochraceus.jpg")`

#### Trends - size at Pt. Grenville

`r insert_figure("rocky-shore_ochre-star.html", "figures/Appendix S.LR.12.1 - Size structure of Pisaster ochraceus in rocky shore habitats Pt Grenville.jpg")`

#### Trends - size at Sokol Point

`r insert_figure("rocky-shore_ochre-star.html", "figures/Appendix S.LR.12.1 - Size structure of Pisaster ochraceus in rocky shore habitats Sokol Pt.jpg")`

#### Trends - status & condition

`r insert_figure("rocky-shore_ochre-star.html", "figures/S.H.12.*_seastar_S&T_ONP.jpg")`

#### Trends - sunflower star

`r insert_figure("rocky-shore_ochre-star.html", "figures/Appendix S.LR.12.3a - Counts of Pycnopodeia helianthoides in rocky shores 2006-2015.jpg")`
